services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - example.env
        ports:
            - "8080:8080"
        command: ./main
        depends_on:
            - db
        restart: always

    db:
        image: postgres:17
        env_file:
            - example.env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U exampleuser"]
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    pgdata: