name: Docker

on:
  push:

jobs:
  build_and_push:
    runs-on: [self-hosted]
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: ghcr.io/egortarasov/avito-intern/app:latest
          push: true
